default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: XMManage_development
  host: localhost

test:
  <<: *default
  database: XMManage_test
  host: localhost

# production:
#   <<: *default
#   database: XMManage_production
#   username: XMManage
#   password: <%= ENV['XMMANAGE_DATABASE_PASSWORD'] %>
